"""Signed-scale GGUF refinement pilot. Keeps hard-packed held-out winners.

This is a targeted experiment, not a full upstream GSQ/RCO implementation.
Routed inputs are generated by the corrected quantized control. Targets use
the ablated BF16 operator weights, not a complete BF16 teacher model.
"""
from __future__ import annotations
import argparse
import ctypes
import hashlib
import json
import os
import struct
import sys
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from tools.pilot_gumbel_formats import CODEBOOKS, BLOCK_SIZES, pack, unpack, source_matrix
import gguf

CODEBOOKS = {**CODEBOOKS, 'Q4_0': list(range(-8, 8))}
BLOCK_SIZES = {**BLOCK_SIZES, 'Q4_0': 32}

def decode(blob: np.ndarray, qtype: str, shape: tuple) -> np.ndarray:
    if qtype != 'Q4_0':
        return unpack(blob, qtype, shape)
    return gguf.quants.dequantize(blob.reshape(shape[0], shape[1] // 32 * 18),
                                 gguf.GGMLQuantizationType.Q4_0).reshape(shape)

def native_quant(weight: torch.Tensor, qtype: str, importance=None) -> np.ndarray:
    folder = ROOT / 'third_party/llama.cpp/build-ninja-release/bin'
    directory = os.add_dll_directory(str(folder))
    library = ctypes.CDLL(str(folder / 'ggml-base.dll'))
    fn = library.ggml_quantize_chunk
    fn.argtypes = [ctypes.c_int, ctypes.c_void_p, ctypes.c_void_p,
                   ctypes.c_int64, ctypes.c_int64, ctypes.c_int64, ctypes.c_void_p]
    fn.restype = ctypes.c_size_t
    values = weight.numpy().astype(np.float32, copy=False)
    blob = np.empty(values.size // BLOCK_SIZES[qtype] * 18, dtype=np.uint8)
    factors = importance[0].numpy().astype(np.float32, copy=True) if importance is not None else None
    n = fn(int(getattr(gguf.GGMLQuantizationType, qtype)), values.ctypes.data,
           blob.ctypes.data, 0, values.shape[0], values.shape[1], factors.ctypes.data if factors is not None else None)
    directory.close()
    if n != blob.size: raise ValueError('Native packed byte count mismatch')
    return blob

def signed_initial(weight, qtype, importance, device='cuda'):
    block = BLOCK_SIZES[qtype]
    w = weight.to(device).reshape(-1, block)
    factor = importance.to(device).reshape(-1, block).clamp_min(1e-8)
    grid = torch.tensor(CODEBOOKS[qtype], device=device, dtype=torch.float32)
    peak = w.abs().amax(1).clamp_min(1e-12)
    best = torch.full_like(peak, float('inf'))
    best_codes = torch.zeros_like(w, dtype=torch.long)
    best_scale = torch.zeros_like(peak)
    for sign in (1., -1.):
        for clip in (.65, .75, .85, .95, 1., 1.1, 1.25):
            scale = sign * clip * peak / grid.abs().max()
            for _ in range(3):
                codes = ((w / scale[:, None])[:, :, None] - grid).square().argmin(-1)
                g = grid[codes]
                scale = ((w * g * factor).sum(1) / (g.square() * factor).sum(1).clamp_min(1e-20))
                scale = scale.half().float()
                scale = torch.where(scale.abs() < 1e-12, sign * torch.full_like(scale, 1e-7), scale)
            codes = ((w / scale[:, None])[:, :, None] - grid).square().argmin(-1)
            error = ((grid[codes] * scale[:, None] - w).square() * factor).sum(1)
            select = error < best
            best = torch.where(select, error, best)
            best_codes[select] = codes[select]
            best_scale[select] = scale[select]
    return best_codes, best_scale

def blob_from_parameters(codes, scales, qtype):
    # Q4_0 shares the IQ4_NL nibble order and 32-element block layout.
    return pack(codes.cpu().numpy(), scales.half().cpu().numpy(),
                'IQ4_NL' if qtype == 'Q4_0' else qtype)

def read_inputs(folder: Path, name: str, expert: int):
    path = folder / (name + '.act')
    with path.open('rb') as file:
        magic = file.read(8)
        experts, width, cap, reserved = struct.unpack('<4I', file.read(16))
        if magic != b'RCOACT01' or (experts, width, reserved) != (512, 640, 0):
            raise ValueError('Invalid routed activation header')
        counts = np.frombuffer(file.read(experts * 8), dtype='<u8')
        expected = 24 + experts * 8 + experts * cap * width * 2
        if path.stat().st_size != expected: raise ValueError('Incomplete activation file')
        file.seek(24 + experts * 8 + expert * cap * width * 2)
        inputs = np.frombuffer(file.read(min(int(counts[expert]), cap) * width * 2), dtype='<f2').copy()
    inputs = torch.from_numpy(inputs.astype(np.float32).reshape(-1, width))
    if not torch.isfinite(inputs).all(): raise ValueError('Nonfinite routed inputs')
    return inputs, int(counts[expert])

def refine(weight, qtype, steps, importance, inputs=None, device='cuda', timings=None):
    started = time.monotonic()
    codes, scale = signed_initial(weight, qtype, importance, device)
    blob = blob_from_parameters(codes, scale, qtype)
    choices = {'signed_initializer': blob}
    if timings is not None: timings['signed_initializer'] = time.monotonic() - started
    refinement_started = time.monotonic()
    w = weight.to(device)
    grid = torch.tensor(CODEBOOKS[qtype], dtype=torch.float32, device=device)
    block = BLOCK_SIZES[qtype]
    normalized = w.reshape(-1, block) / scale[:, None]
    distance = (normalized[:, :, None] - grid).square()
    spacing = (grid[1:] - grid[:-1]).abs().median().square().clamp_min(1.)
    logits = torch.nn.Parameter((-distance / spacing).detach())
    magnitude = torch.nn.Parameter(scale.abs().clamp_min(1e-12).log().detach())
    sign = scale.sign()
    optimizer = torch.optim.Adam([{'params': logits, 'lr': .025}, {'params': magnitude, 'lr': .008}])
    factor = importance.to(device)
    x = inputs.to(device) if inputs is not None and len(inputs) else None
    diagonal_power = (w.square() * factor).mean().clamp_min(1e-12)
    denominator = ((w @ x.T).square().mean().clamp_min(1e-12) if x is not None else diagonal_power)
    for step in range(steps):
        optimizer.zero_grad(set_to_none=True)
        probabilities = F.gumbel_softmax(logits, tau=1 - .85 * step / max(steps - 1, 1), dim=-1)
        approx = ((probabilities * grid).sum(-1) * (sign * magnitude.exp())[:, None]).reshape(w.shape)
        residual = approx - w
        loss = ((residual @ x.T).square().mean() if x is not None
                else (residual.square() * factor).mean()) / denominator
        if x is not None:
            loss = loss + .1 * (residual.square() * factor).mean() / diagonal_power
        if not torch.isfinite(loss): raise ValueError('Nonfinite refinement loss')
        loss.backward()
        optimizer.step()
        with torch.no_grad(): magnitude.clamp_(-25, 10)
        if step + 1 in (48, 96, steps):
            with torch.no_grad():
                choices[f'refined_{step+1}'] = blob_from_parameters(logits.argmax(-1), sign * magnitude.exp(), qtype)
                if timings is not None: timings[f'refined_{step+1}'] = time.monotonic() - refinement_started
    return choices

def score(weight, blob, qtype, importance, heldout=None):
    reconstruction = torch.from_numpy(decode(blob, qtype, tuple(weight.shape)))
    if not torch.isfinite(reconstruction).all(): raise ValueError('Nonfinite packed reconstruction')
    error = reconstruction - weight
    result = {'weighted_sse': float((error.square() * importance).sum()),
              'weighted_power': float((weight.square() * importance).sum()),
              'weight_sse': float(error.square().sum()), 'source_power': float(weight.square().sum())}
    if heldout is not None and len(heldout):
        result.update(output_sse=float((error @ heldout.T).square().sum()),
                      output_power=float((weight @ heldout.T).square().sum()))
    return result

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--source', type=Path, default=Path('data/source'))
    p.add_argument('--output', type=Path, default=Path('data/optimization-48h/pilot'))
    p.add_argument('--layers', default='0,23,47')
    p.add_argument('--experts', default='0,127,255')
    p.add_argument('--rows', type=int, default=256)
    p.add_argument('--steps', type=int, default=48)
    p.add_argument('--train-inputs', type=Path)
    p.add_argument('--validation-inputs', type=Path)
    p.add_argument('--formats', nargs='+', default=['IQ4_NL','Q2_0','Q4_0'], choices=list(CODEBOOKS))
    p.add_argument('--imatrix', type=Path, default=Path('data/calibration/selected/imatrix-hybrid-128.gguf'))
    args = p.parse_args()
    if bool(args.train_inputs) != bool(args.validation_inputs): p.error('Both disjoint input sets are required')
    args.output.mkdir(parents=True, exist_ok=True)
    from tools.quantize_edited import read_imatrix
    imatrix, _ = read_imatrix(args.imatrix)
    for layer in map(int, args.layers.split(',')):
        name = f'blk.{layer}.ffn_down_exps.weight'
        for expert in map(int, args.experts.split(',')):
            stem = f'layer{layer}-expert{expert}'
            report_path = args.output / f'{stem}.json'
            if report_path.exists(): continue
            weight = source_matrix(args.source, f'model.language_model.layers.{layer}.mlp.experts.down_proj', expert, args.rows)
            values, counts = imatrix[name]
            importance = torch.from_numpy(np.tile(values[expert] / max(counts[expert], 1), (weight.shape[0], 1))).clamp_min(1e-8)
            train = valid = None
            if args.train_inputs:
                train, _ = read_inputs(args.train_inputs, name, expert)
                valid, _ = read_inputs(args.validation_inputs, name, expert)
                if len(train) < 8 or len(valid) < 4: raise ValueError('Pilot expert has inadequate routed input coverage')
            report = {'layer':layer,'expert':expert,'shape':list(weight.shape),'results':[],
                      'selection_reference':'disjoint routed inputs' if valid is not None else 'diagonal calibration proxy'}
            for qtype in args.formats:
                start = time.monotonic()
                torch.manual_seed(1729 + layer * 512 + expert)
                torch.cuda.reset_peak_memory_stats()
                choices = {'native':native_quant(weight, qtype),
                           'native_calibrated':native_quant(weight,qtype,importance)}
                if qtype in ('IQ4_NL','Q2_0'):
                    old_path = ROOT / 'data/variants' / f'{name.replace(".","_")}.{qtype}.bin'
                    with old_path.open('rb') as old:
                        row_bytes = 640 // BLOCK_SIZES[qtype] * 18
                        old.seek(expert * 2560 * row_bytes)
                        choices['previous'] = np.frombuffer(old.read(weight.shape[0] * row_bytes), dtype=np.uint8).copy()
                timings = {}
                choices.update(refine(weight,qtype,args.steps,importance,train,timings=timings))
                scores = {method:score(weight,blob,qtype,importance,valid) for method,blob in choices.items()}
                key = 'output_sse' if valid is not None else 'weighted_sse'
                best = min(scores, key=lambda method:scores[method][key])
                for method, blob in choices.items(): blob.tofile(args.output / f'{stem}-{qtype}-{method}.bin')
                result = {'format':qtype,'selected':best,'scores':scores,'seconds':time.monotonic()-start,
                          'method_seconds':timings,'gpu_peak_bytes':torch.cuda.max_memory_allocated()}
                report['results'].append(result)
                print(json.dumps({'layer':layer,'expert':expert,**result}), flush=True)
            report_path.write_text(json.dumps(report,indent=2)+'\n')

if __name__ == '__main__': main()
